# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://dpa-newslab.github.io/apps.dpa-newslab.com/
title: G7 News App
logo: img/logo.svg
email: martin.virtel@dpa-info.vom
author: Martin Virtel
description: > # "Write an awesome description for your new site here. 
  "The G7 News app is provided to participants of the G7 Summit 2015 by dpa Infocom."
copyright: '<a href="http://www.dpa-info.com">dpa-Infocom GmbH</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

#social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap
#  - title: linkedin
#    url: 
